### ISSUE TITLE
Training epochs

### ISSUE THREAD

**Issue by sihyun-yu** [LTH14/mar#12]
Hi,

thanks for releasing the code this wonderful project! I am a bit confused of training epochs because in the main text it states the model is trained on 800 epochs but in Appendix it states the model is trained on 400 epochs. Can you clarify this? Thanks in advance!

**Comment by LTH14** [comment]
Thanks for your interest! For all ablations studies, we use models trained with 400 epochs (Table 1-3, Figure 4-6). Only models in Table 4 and Figure 7 (which are the models released in this repo) are trained for 800 epochs.

**Comment by sihyun-yu** [comment]
Thanks for your reply!
