### ISSUE TITLE
Loss for training KL-VAE

### ISSUE THREAD

**Issue by Vinnieassaulter** [LTH14/mar#13]
Hello! May I ask if you used VQ-16 similar perceptual loss or just reconstruction loss and KL divergence when training KL-VAE?

**Comment by LTH14** [comment]
Hi! Please see the configuration here https://github.com/CompVis/latent-diffusion/blob/main/models/first_stage_models/kl-f16/config.yaml#L7-L12. Just the same as LDM's KL-VAE, we use reconstruction loss, perceptual loss, KL divergence, and GAN loss.
