### ISSUE TITLE
Latent Dimensions of VAE

### ISSUE THREAD

**Issue by Vinnieassaulter** [LTH14/mar#15]
What great work!

Hello! I would like to ask a question about the feature dimension of the output of VAE-tokenizer. As we noticed that its output defaults to 16 dimensions and goes up to 768/1024/1280 dimensions after a linear layer at the beginning of diffusion phase, is this for some particular reason? Also, we observed in LDM that they compared the reconstruction effect on very low (~ as low as two dimensions) dimensions (parameter c in table.8), may I ask if you also experimented on these dimensions? Thank you very much!

**Comment by LTH14** [comment]
Thanks! We choose 16 to be consistent with LDM's official KL-16 tokenizer. To denoise the token, the MLP in diffusion loss should have enough capacity, as demonstrated in Table 3 of the paper.

We did not conduct a thorough study of the feature dimension in VAEs. However, based on our experience, when the VAE's downsampling factor is 16 and the feature dimension is less than 16 (e.g., 8), the reconstruction quality is significantly worse.

**Comment by Vinnieassaulter** [comment]
Thank you very much for your reply and sharing! According to your experience, can we assume that the feature dimensions are correlated with the downsampling rate?

**Comment by LTH14** [comment]
The size of the image after tokenization is ```(256 x 256 / (s x s) x d)```. The reconstruction performance is largely correlated with this number, which indicates the compression ratio of the tokenization.
