### ISSUE TITLE
Training settings for MAR series

### ISSUE THREAD

**Issue by HuangOwen** [LTH14/mar#16]
Hi Authors,

Thanks for your awesome work! I am trying to reproduce the training results and I notice that the training scripts provided have a different setting (400 epoch, 3 blocks, 1024 channels) with the pre-trained model evaluation (800 epoch, 8 blocks, 1280 channels). May I know what is the exact settings for producing the MAR series in Table 4 of your paper? Thanks in advance.

**Comment by LTH14** [comment]
Thanks for your interest! The provided training script is for our default setting in the ablation studies. Please refer to Appendix B of our paper for the implementation details of Table 4. It is almost the same as the default setting, except for training epochs (800) and MLP size (8 blocks, 1280 channels).
