### ISSUE TITLE
Buffer Size for Class Condition

### ISSUE THREAD

**Issue by zhuole1025** [LTH14/mar#21]
Hi, thanks for your great work!

I am trying to implement a mage with improvements in mar. For the class-conditional embedding, I noticed that mar set a `buffer_size=64`. However, the class condition is only a single embedding with length 1, and the class embedding is duplicated for `buffer_size` times. Could you explain the reason for this mismatch?

**Comment by LTH14** [comment]
Thank you for your interest! In MAGE training, we pad the unmasked tokens with the mask token [M] to 50% of the sequence length. During inference, we extend this padding to 100% of the sequence length. This approach ensures that the encoder has sufficient computation, especially when the masking ratio is high.

On the other hand, MAR's encoder, following the MAE approach, is fully sparse—meaning all masked tokens are dropped. To compensate for this and provide the encoder with enough computation, we introduce a "buffer." While all of these buffers are class embeddings, each of the 64 buffers has unique position embeddings. This buffer primarily serves to simulate the padding mask token's role in MAGE.

**Comment by zhuole1025** [comment]
Thanks for your prompt reply! It is great to know such interesting differences between mage and mar. 

If I understand correctly, these buffer tokens are only designed and used for encoder learning? I also noticed that mage only applys position embeddings to the decoder part. Besides, mar also removes the need for the `fake_class_token`, which is claimed to boost generation performance in mage. Can I assume that this token is important when considering both SSL and generative modeling, and becomes redundant when we only target generation?

**Comment by LTH14** [comment]
MAGE also applies position embedding to the encoder -- it is in [BertEmbeddings](https://github.com/LTH14/mage/blob/main/models_mage.py#L106) (sorry it is hidden here because of the legacy issue from JAX implementation). The fake_class_token is replaced with [fake_latent](https://github.com/LTH14/mar/blob/main/models/mar.py#L62) for unconditional generation. [Padding with class token](https://github.com/LTH14/mage/blob/main/models_mage.py#L321) in MAGE improves the performance quite marginally. Therefore for simplicity, we also remove it in MAR.

**Comment by zhuole1025** [comment]
Thanks! You just solved all the puzzles for me, and I am ready to train a class-conditional MAGE now :)

**Comment by lorenmt** [comment]
> Thank you for your interest! In MAGE training, we pad the unmasked tokens with the mask token [M] to 50% of the sequence length. During inference, we extend this padding to 100% of the sequence length. This approach ensures that the encoder has sufficient computation, especially when the masking ratio is high.
> 
> On the other hand, MAR's encoder, following the MAE approach, is fully sparse—meaning all masked tokens are dropped. To compensate for this and provide the encoder with enough computation, we introduce a "buffer." While all of these buffers are class embeddings, each of the 64 buffers has unique position embeddings. This buffer primarily serves to simulate the padding mask token's role in MAGE.

Just to follow up on this, can we then consider this buffer as a form of register as proposed in this paper: https://arxiv.org/abs/2309.16588, which is added simply to expand representation space for the transformers?

**Comment by LTH14** [comment]
@lorenmt Good point, I think the implementation of our buffer is almost the same as the register. However, we also notice that, if the MAR encoder is not sparse (i.e. always pad to 256 tokens using mask tokens), then adding additional buffers is not useful, which is a bit different from the results in the register paper (where the register can always improve the performance). Therefore, my feeling is our buffer here is mainly to introduce more computation in the encoder, while the register is used to make the feature map cleaner.

**Comment by lorenmt** [comment]
Appreciate the insights here. But if just expanding the representation space, why not make the buffer tokens fully learnable instead of initiating them as the replica of class embedding? I feel like such design decision makes the method design less elegant? :/

**Comment by LTH14** [comment]
The positional embeddings on the buffers are learnable and different for each buffer, which should correspond to your suggestions of "fully learnable buffer tokens". The replica of class embedding is just for conditioning.

**Comment by lorenmt** [comment]
Got it. Thanks!
