### ISSUE TITLE
About the mask schedule during training

### ISSUE THREAD

**Issue by zythenoob** [LTH14/mar#22]
First of all, thank you for the awesome work!

I'd like to ask about the sampling of mask ratio during training: why is the ratio [0.7, 1.0] instead of [0, 1.0]?
To me picking the mask ratio in [0, 1.0] seems more fit with the inference process.
This wasn't explained in the paper, so I wonder how does the mask ratio range impact the training dynamics as well as the inference quality?

**Comment by LTH14** [comment]
Thanks for your interest! We follow MAE for this sparse encoder design. Using [0.7, 1.0] is to reduce the training cost -- the encoder will only see at most 30% sequence during training, which largely reduces the computation (both memory and speed). This allows us to train larger models (like MAR-H) on our GPUs.

**Comment by zythenoob** [comment]
Thank you for the fast reply. So technically speaking, given enough computational resources, lowering the min bound to, say 0.3, will improve the overall performance of this method?

**Comment by LTH14** [comment]
We once ablated this and the performance was not significantly improved when I reduced the min masking ratio from 0.7 to 0.6 and 0.5.

**Comment by zythenoob** [comment]
Got it, thanks!
