### ISSUE TITLE
How should inference be performed when using VQ-16 (discrete)? During decoding, should we use the AR output for VQ and then decode?

### ISSUE THREAD

**Issue by Tom-zgt** [LTH14/mar#23]
@LTH14 How should inference be performed when using VQ-16 (discrete)? During decoding, should we use the AR output for VQ and then decode?
Which layer should we use as the input for the AR? And how do we convert the AR output into an image?
<img width="473" alt="屏幕快照 2024-08-21 下午3 43 02" src="https://github.com/user-attachments/assets/fe50c325-8194-49fb-9d31-3bf89c8cddae">
<img width="496" alt="屏幕快照 2024-08-21 下午3 43 12" src="https://github.com/user-attachments/assets/ca7831c7-8f2f-45ac-8e73-598dab5830dd">

**Comment by LTH14** [comment]
We take the ```h``` before quantization as the target of the MAR+DiffLoss. After generating such ```h```, we quantize and decode it. In other words, the encoder and quant_conv are regarded as "encoder", while the quantization, post_quant_conv and decoder are regarded as "encoder".

**Comment by Tom-zgt** [comment]
thanks for your reply.
