### ISSUE TITLE
Inference details of an ablation experiment.

### ISSUE THREAD

**Issue by tgxs002** [LTH14/mar#26]
Dear author, thank you for your interesting work! I would like to know the inference details of this experiment:
![test](https://github.com/user-attachments/assets/b6e1fce3-0ae1-4a1b-ad3e-b4d5deae040b)
Do you randomly select the next token to predict, or follow a certain pattern?
Looking forward to your reply!

**Comment by LTH14** [comment]
We randomly select a token to predict
