### ISSUE TITLE
CFG for cross-entropy

### ISSUE THREAD

**Issue by shaochenze** [LTH14/mar#38]
Hi @LTH14 ,
In Table 1, I noticed that models trained using cross-entropy loss also support CFG. Could you elaborate on the methodology employed to achieve this, or provide some reference?

**Comment by LTH14** [comment]
Please see [Muse](https://arxiv.org/pdf/2301.00704)'s CFG strategy in their section 2.7

**Comment by shaochenze** [comment]
Got it. Thanks a lot!
