### ISSUE TITLE
About Encoder and Decoder in MAE

### ISSUE THREAD

**Issue by RohollahHS** [LTH14/mar#42]
Congrats for the amazing work. Really liked it.

The encoder in MAE takes only known tokens, and the decoder takes both known and unkown tokens. Did you try using only a decoder without an encoder? I mean, a multi-layer transformer, similar to a decoder, but with double the size of the encoder and decoder, that takes both known and unknown tokens and predicts z?

Thanks

**Comment by LTH14** [comment]
Thanks for your interest! We follow MAE just because it is more computationally efficient so that we can train MAR-H on our resources. Using a decoder only is definitely possible and in our experiments it has almost the same performance.
