### ISSUE TITLE
Dataset used for training...

### ISSUE THREAD

**Issue by Nobody-Zhang** [LTH14/mar#50]
Thanks for the amazing work!
I am trying to reproduce the FIDs.
Could you please tell me the dataset you have used for training?
I tried training on the 'winter21_whole.tar.gz'(1.1T, 21K), but that took much longer than I had expected.
![image](https://github.com/user-attachments/assets/0caaa242-f297-41ca-b6d0-f6f5192c8ddb)
@LTH14

**Comment by LTH14** [comment]
We use the standard ILSVRC2012

**Comment by Nobody-Zhang** [comment]
Thanks a lot!
