### ISSUE TITLE
About training with cached vae latents

### ISSUE THREAD

**Issue by RohollahHS** [LTH14/mar#52]
Are the results of training with images and training with cached vae latents the same? I think in the case of cached vae latents we can no longer use center crop augmentation.

**Comment by LTH14** [comment]
The latent is computed using images after the center crop. The results of training with images and latents should be the same as there is no randomness besides random flips in the augmentation.

**Comment by RohollahHS** [comment]
Thanks for the clarification, I thought the center_crop function was a type of augmentation.
