### ISSUE TITLE
About the positional encodings of diffusion MLP.

### ISSUE THREAD

**Issue by whwjdqls** [LTH14/mar#54]
Hi great work!

I found an issue that the PE for diffusion MLP is not required as the decoder already has the  position information.
Is this proven by experiments? because i am adopting mar to time series data and I'm seeing nan losses when not using PE for diffusion MLP. 

thanks in advance!

**Comment by LTH14** [comment]
Yes the current PE for the diffusion MLP is just a legacy issue in the code. I tried with and without this PE and the performance gap is ineligible. However since our pre-trained large model is with this PE, we still keep it in the current codebase.

**Comment by whwjdqls** [comment]
great! Thanks for the prompt reply! :)
