### ISSUE TITLE
Will mar work when img_size=64 or img_size=128?

### ISSUE THREAD

**Issue by fengyang0317** [LTH14/mar#59]
Thank you for this excellent work. I am wondering have you tried img_size=64 or img_size=128?

I am able to reproduce the img_size=256 results. I tried to change img_size to 64 and redo the feature caching and training. All the other training hyper-parameters are kept the unchanged. The 64x64 FID computed with [VIRTUAL_imagenet64_labeled.npz](https://openaipublic.blob.core.windows.net/diffusion/jul-2021/ref_batches/imagenet/64/VIRTUAL_imagenet64_labeled.npz) is about 14. I tried to reduce the buffer_size, base_lr and weight_decay. But these does not help.

The seq_h and seq_w will be 4 when the img_size=64. Will mar work under this resolution?

**Comment by LTH14** [comment]
When using img_size=64 you should change the tokenizer -- the tokenizer is trained with img_size=256

**Comment by fengyang0317** [comment]
I see. Thanks
