### ISSUE TITLE
How is 0.2325 calculated?

### ISSUE THREAD

**Issue by shuowang666** [LTH14/mar#62]
Hi,
Thanks for your great work！
I don't really understand why this operation is necessary, could you please explain? As you mentioned in the other issues: 0.2325 = 1 / torch.std(vae.encode(x).sample()), my understanding is that for each Image in the training set, this value(i.g. vae.encode(x).sample()) is calculated just sample once for one image, not sure whether that's accurate or not.
![image](https://github.com/user-attachments/assets/76593d73-4f53-4833-9424-d7d520dfdba4)

**Comment by LTH14** [comment]
The 0.2325 is calculated on all tokens in the entire ImagegNet dataset.

**Comment by shuowang666** [comment]
For example, the shape of the entire dataset tokens is (b, c, h, w), b is the number of samples in the dataset, for all tokens calculate std and then 1/std = 0.2325. Do I understand this correctly?

**Comment by LTH14** [comment]
Yes -- simply torch.std(x) where x is this b, c, h, w dataset

**Comment by shuowang666** [comment]
Thank you for your help!

**Comment by tau-yihouxiang** [comment]
In ImageNet dataset, after calculation, I found that the latents inferred by the petrained vae have mean = -8.889777183532715 std = 8.755897521972656. How to calculate the scale_factor = 0.2325?

**Comment by shuowang666** [comment]
Hi, 
Why ignore the mean just for {token / std}? Have you tried the {(token - mean) / std} effect?

**Comment by LTH14** [comment]
This just follows the original LDM implementation which only divides the std. I think subtracting the mean is also reasonable, but I feel this might not significantly affect the performance as such a constant should be learned easily (unlike the scale factor which could affect the SNR)

**Comment by shuowang666** [comment]
Thanks a lot. I get it!
