### ISSUE TITLE
About diffloss

### ISSUE THREAD

**Issue by RohollahHS** [LTH14/mar#63]
Hi,

In this part https://github.com/LTH14/mar/blob/fe470ac24afbee924668d8c5c83e9fec60af3a73/models/mar.py#L232-L238, why you did not filter unmasked tokens (by mask) and just pass the masked tokens to the `self.diffloss`? You then use the mask to compute the loss only for masked tokens.

Thanks

**Comment by LTH14** [comment]
Both implementations are ok

**Comment by RohollahHS** [comment]
Thanks for the prompt response.
