### ISSUE TITLE
MAR used for image restoration

### ISSUE THREAD

**Issue by chengliang0109** [LTH14/mar#65]
Hello, I'm a beginner. Can MAR be used for image restoration? For example, image dehaze and image deraining. If MAR is used for image restoration, what parts would likely need modification? Also, if using MAR for image restoration, can we avoid using VAE and perform autoregressive restoration directly in the pixel space?

**Comment by chengliang0109** [comment]
For example, image dehaze and image deraining.

**Comment by LTH14** [comment]
We haven't explored that, but it would be an interesting direction.
