### ISSUE TITLE
Comparison of results before and after using diff_loss

### ISSUE THREAD

**Issue by shuowang666** [LTH14/mar#66]
Hi, Tianhong

Have you tried dropping the diff_loss and using MSE loss directly on the VAE's latent embedding in the second stage?

**Comment by LTH14** [comment]
Yes -- that does not work, which we included in Appendix D2.

**Comment by shuowang666** [comment]
Thank you for your reply!

**Comment by csgeekhuang** [comment]
> Yes -- that does not work, which we included in Appendix D2.

actually, it is the D3 part
