### ISSUE TITLE
Differences between Latent Space and Pixel Space

### ISSUE THREAD

**Issue by OK932001** [LTH14/mar#67]
Can MAR be used without a VAE, and can it perform autoregressive generation directly in pixel space?

**Comment by LTH14** [comment]
Yes -- we conducted a preliminary experiment on ImageNet 64x64, grouping every 4x4 pixels into one token for Diffusion Loss to model. A MAR-L+DiffLoss model trained for 400 epochs achieved an FID of 2.93. This result will also be included in our camera-ready version.

**Comment by SwindBlowing** [comment]
> Yes -- we conducted a preliminary experiment on ImageNet 64x64, grouping every 4x4 pixels into one token for Diffusion Loss to model. A MAR-L+DiffLoss model trained for 400 epochs achieved an FID of 2.93. This result will also be included in our camera-ready version.

Hi, I'm also trying to train MAR-based models directly in pixel space. Could you please share the loss curve for MAR-L+DiffLoss with us for reference? Thank you!

**Comment by LTH14** [comment]
> > Yes -- we conducted a preliminary experiment on ImageNet 64x64, grouping every 4x4 pixels into one token for Diffusion Loss to model. A MAR-L+DiffLoss model trained for 400 epochs achieved an FID of 2.93. This result will also be included in our camera-ready version.
> 
> Hi, I'm also trying to train MAR-based models directly in pixel space. Could you please share the loss curve for MAR-L+DiffLoss with us for reference? Thank you!

Sure, here you go -- the optimal CFG is larger than 3.0 but we always record FID with cfg=3.0 for online evaluation.

<img width="505" alt="Image" src="https://github.com/user-attachments/assets/e5ec5f30-dbfd-4e49-a650-7553c34aa0b5" />

<img width="508" alt="Image" src="https://github.com/user-attachments/assets/44790750-4237-468b-8cc5-959e88523328" />
