### ISSUE TITLE
noise_schedule setting

### ISSUE THREAD

**Issue by wangherr** [LTH14/mar#70]
Have you tried using other noise schedules besides the default 'cosine'? 

When using the 'cosine' noise scheduler, the output tends to be a black image during the initial epochs. 

Does the same occur with the 'linear' noise scheduler?

**Comment by wangherr** [comment]
I find that "cosine" may introduce subtle errors, though I'm not entirely sure.

**Comment by wangherr** [comment]
When using ‘cosine’，

> 
    def _predict_xstart_from_eps(self, x_t, t, eps):
        assert x_t.shape == eps.shape
        return (
            _extract_into_tensor(self.sqrt_recip_alphas_cumprod, t, x_t.shape) * x_t
            - _extract_into_tensor(self.sqrt_recipm1_alphas_cumprod, t, x_t.shape) * eps
        )

sqrt_recip_alphas_cumprod[999] will have an extremely large value, significantly deviating from the other values in the sequence.

**Comment by adaxigua** [comment]
When using ‘cosine’，

> 
    def _predict_xstart_from_eps(self, x_t, t, eps):
        assert x_t.shape == eps.shape
        return (
            _extract_into_tensor(self.sqrt_recip_alphas_cumprod, t, x_t.shape) * x_t
            - _extract_into_tensor(self.sqrt_recipm1_alphas_cumprod, t, x_t.shape) * eps
        )

sqrt_recip_alphas_cumprod[999] will have an extremely large value, significantly deviating from the other values in the sequence. This discrepancy often leads to NaN values during the initial epochs.

**Comment by LTH14** [comment]
I didn't pay much attention at the early stage of the training as it is typically unstable. Cosine works slightly better than linear for the final FID.

**Comment by adaxigua** [comment]
That's right. However, I suspect that correcting this significantly deviating value might be beneficial.

> 
        from diffusion import create_diffusion
        
        gen_diffusion = create_diffusion(timestep_respacing='1000', noise_schedule="cosine")
        
        for i in range(1000):
            print(
                i,
                gen_diffusion.sqrt_recip_alphas_cumprod[i]
            )

> 
    0 1.000020642751578
    1 1.000043714902638
    2 1.0000692167333955
    3 1.0000971485535928
    4 1.0001275107025092
    5 1.0001603035489695
    6 1.0001955274913557
    7 1.000233182957619
    8 1.0002732704052921
    9 1.000315790321503
    10 1.0003607432229893
    ...
    990 71.29821121567663
    991 80.2099357294196
    992 91.66794145559187
    993 106.94536899820552
    994 128.3338714448183
    995 160.41675497101292
    996 213.88840065370766
    997 320.83195172460955
    998 641.6631243437595
    999 20291.169634661146
