### ISSUE TITLE
Reproduce the results of Table 1

### ISSUE THREAD

**Issue by Doraemonzzz** [LTH14/mar#72]
Thank you for open-sourcing the code, I am very interested in Table 1. I noticed that the repository does not provide the training part for AR or MAR. Do you have plans to open-source it? Or can this be achieved by modifying `engine_mar.py`?

**Comment by LTH14** [comment]
This repo contains the training for MAR -- please check the "Training" section in the readme. To keep the current repo clean, we don't release the AR version -- but it is very easy to implement by modifying the models/mar.py.

**Comment by csgeekhuang** [comment]
> This repo contains the training for MAR -- please check the "Training" section in the readme. To keep the current repo clean, we don't release the AR version -- but it is very easy to implement by modifying the models/mar.py.

If possible, would you be willing to release the code for the autoregressive version? I’m finding it quite challenging to train the model from scratch, and having access to your implementation would be incredibly helpful for my research.
