### ISSUE TITLE
VAE training

### ISSUE THREAD

**Issue by swasler** [LTH14/mar#73]
Hi @LTH14 I have a question for the VAE training.

Your project code doesn't involve VAE training, which I completely understand since you only need a pre-trained VAE to extract tokens. I now want to apply the model to some single-channel images, which requires me to retrain a VAE model. I have modified some of the corresponding code, however, I found that in AutoencoderKL's forward method, training uses **self.training_step**, but the **training_step** method is not mentioned anywhere in the project. I'd like to see the details of the training code for modification purposes - could you tell me where I can find the **training_step** method you used for reference? 

Thank you very much!

**Comment by LTH14** [comment]
We follow the VQGAN training with KL-VAE. Please check https://github.com/CompVis/taming-transformers and https://github.com/CompVis/latent-diffusion/blob/main/configs/autoencoder/autoencoder_kl_16x16x16.yaml

**Comment by shaochenze** [comment]
Hi @LTH14, I noticed a difference between your VAE model and the one used in latent diffusion: the attention layer in decoder is removed. Could you share the insights?

**Comment by LTH14** [comment]
This does not matter much -- we remove it simply because of memory issue.

**Comment by swasler** [comment]
Thank you for your clarification
