### ISSUE TITLE
Why Are Buffer Tokens Still Needed in the Decoder?

### ISSUE THREAD

**Issue by Becomebright** [LTH14/mar#77]
Hi, thanks for your inspiring work!

As mentioned in https://github.com/LTH14/mar/issues/21#issuecomment-2295315297, buffer tokens ensure the encoder has sufficient computation. However, I’m curious—why are they still necessary in the decoder?

Looking forward to your insights!

**Comment by LTH14** [comment]
I just kept it for simplicity -- keeping one buffer token in the decoder (for the class token) should be enough.
